### ISSUE TITLE
1.0.6 BC break?

### ISSUE THREAD

**Issue by nikolajosipovic** [ardalis/SmartEnum#41]
Hi, seems 1.0.6 NuGet version introduced an additional constraint on TValue to be of `struct` type, but I can't really find when and where this happened here in the repo. Also can't really find the previous versions tags. Am I missing something? :)

**Comment by ardalis** [comment]
I wasn't applying tags until this version, sorry. Do you have an example of a non-struct TValue you could share?

**Comment by nikolajosipovic** [comment]
Hi Ardalis, 1.0.5 doesn't have the struct constraint on TValue. 
Seems it was introduced here: https://github.com/ardalis/SmartEnum/commit/1c9bf3ede229fcb561330719cd13af67dcf92ad7#diff-b71ca71881242d3857a980ff13d4309dR34

**Comment by ardalis** [comment]
Right, that was a major PR introduced by @aalmada which had a big positive perf impact. What negative impact are you seeing from the constraint? What scenario is it limiting?

Remember SmartEnum's primary goal is replacing the standard `enum` type and making it better by having each option be a class rather than a primitive. A standard `enum` can only be a very short list of types:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/enum

> The approved types for an enum are byte, sbyte, short, ushort, int, uint, long, or ulong.

**Comment by nikolajosipovic** [comment]
Thanks. I was using it with `string` values.
I don't have a large codebase depending on SmartEnum and string as a value so I can get away with refactoring the code.

**Comment by ardalis** [comment]
Ok, thanks. Of course if you stick with 1.0.5 you should be fine, too. Unless I hear that this is breaking a lot of other people, though, I think I'm fine to have SmartEnum expect a struct Value going forward.
