### ISSUE TITLE
Do SmartEnum classes work with AuthorizationFilterAttribute

### ISSUE THREAD

**Issue by fetters5** [ardalis/SmartEnum#89]
I may be missing something but for some reason I was hoping that it would act like an enum or const string where    
Permission.ManageRoles.Name  ="ManageRoles" or ermission.ManageRoles.Value =4   but it does not. I get the following error when trying to add to a custom authorization attribute which works for our enums or const strings 
 [CustomAuthorize(Permission.ManageRoles.Name)]

An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type

Any help would be much appreciated

**Comment by ardalis** [comment]
No, since they're not actually constant values, but classes, they won't work in this scenario. I'm not sure if there's an easy workaround aside from adding some actual constants to your SmartEnum subclass to represent your values. If there aren't many, that might be easiest.

```csharp
using Ardalis.SmartEnum;

public sealed class TestEnum : SmartEnum<TestEnum>
{
   public const int ValueOne = 1;
   public const int ValueTwo = 2;
   public const int ValueThree = 3;
    public static readonly TestEnum One = new TestEnum(nameof(One), ValueOne);
    public static readonly TestEnum Two = new TestEnum(nameof(Two), ValueTwo);
    public static readonly TestEnum Three = new TestEnum(nameof(Three), ValueThree);

    private TestEnum(string name, int value) : base(name, value)
    {
    }
}
```

Then you could say `[CustomAuthorize(Permission.ManageRoles.ValueOne)]` perhaps. Would work similarly for names if you prefer a string. It's not ideal but could be a workaround for you.

**Comment by fetters5** [comment]
Thanks Steve, that is actually the route I was planning to take if there was not a better solution.  For us the pros still out weigh the cons.

Btw thanks for making this library it has been useful in other cases where we needed to convert enums in to something smarter
